[tasks.run]
description = "Build the project."
command = "cargo"
args = [
  "run",
  "--bin", "helloworld-server"
]

[tasks.build]
description = "Build the project for Linux target using Docker"
command = "cross"
args = [
    "build",
    "--release", 
    "--bin", "helloworld-server",
    "--target", "x86_64-unknown-linux-gnu"
]

[tasks.docker-build]
description = "Build the project for Linux target using Docker"
dependencies = ["build"]
command = "docker"
args = [
  "build", "--target", "prod", "-t", "helloworld-server", "."
]


[tasks.push-dockerhub]
description = "Push the project to Docker Hub"
dependencies = ["docker-build"]
script = [
    '''
    docker tag helloworld-server:latest hogehoge.dkr.ecr.ap-northeast-1.amazonaws.com/helloworld-server:latest
    aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin hogehoge.dkr.ecr.ap-northeast-1.amazonaws.com
    docker push hogehoge.dkr.ecr.ap-northeast-1.amazonaws.com/helloworld-server:latest
    '''
]

[tasks.deploy]
description = "Deploy to Docker Hub"
dependencies = ["push-dockerhub"]
script = [
    '''
    ecs-deploy \
        -r ap-northeast-1 \
        --cluster helloworld \
        --service-name helloworld-server \
        --image hogehoge.dkr.ecr.ap-northeast-1.amazonaws.com/helloworld-server:latest \
        -t 600 \
        --verbose
    '''
]
